app = "$APP_NAME"
primary_region = "ams"

[env]
  PORT = "8000"
  DJANGO_SETTINGS_MODULE = "project.settings.production"

[[mounts]]
  source = "db"
  destination = "/app/db"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"