# Generated by Django 4.2.4 on 2023-08-09 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0002_flyaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlyAccount',
        ),
    ]
