# Generated by Django 4.2.4 on 2023-08-09 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0003_delete_flyaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='postgresdatabase',
            name='fly_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backups.flyaccount'),
        ),
    ]
