# Generated by Django 4.2.4 on 2023-08-09 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0004_flyaccount_postgresdatabase_fly_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postgresdatabase',
            name='fly_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backups.flyaccount'),
        ),
    ]
