# Generated by Django 4.2.4 on 2023-08-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0005_alter_postgresdatabase_fly_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='flyaccount',
            name='name',
            field=models.CharField(default='fly app', max_length=100),
            preserve_default=False,
        ),
    ]
