# Generated by Django 4.2.4 on 2023-08-09 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0007_alter_postgresdatabase_app_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='s3bucket',
            name='path',
        ),
    ]
